export const ACTION_SET_BEFORE_ROUTER = 'actionSetBeforeRouter'
export const ACTION_SET_LOADING = 'actionSetLoading'
export const ACTION_FINISH_LOADING = 'actionFinishLoading'
export const ACTION_CLEAR_LOADING = 'actionClearLoading'
export const ACTION_SET_ERROR = 'actionSetError'
export const ACTION_CLEAR_ERROR = 'actionClearError'
